import { Volonteers } from "./vol_types";

export const volonteers: Volonteers = [
  {
    id: "vln01",
    firstName: "John",
    secondName: "Rick",
    avatar: "https://www.flaticon.com/free-icon/man_4140061",
    age: 38,
    address: "Street, Town",
    country: "Sweden",
    sex: "male",
    phone: "+38004558887",
    donation: [
      { date: new Date("2023-11-01"), amount: 2000 },
      { date: new Date(), amount: 8000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: false,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln02",
    firstName: "Sam",
    secondName: "Got",
    avatar: "https://www.flaticon.com/free-icon/doctor_14244649",
    age: 27,
    address: "Street, Town",
    country: "UK",
    sex: "male",
    phone: "+38004974887",
    donation: [
      { date: new Date("2023-02-09"), amount: 25487 },
      { date: new Date(), amount: 32587 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: false,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: false,
    isSelected: false,
  },
  {
    id: "vln03",
    firstName: "Lean",
    secondName: "Rihn",
    avatar: "https://www.flaticon.com/free-icon/womale_14671574",
    age: 54,
    address: "Street, Town",
    country: "Poland",
    sex: "female",
    phone: "+38031454",
    donation: [
      { date: new Date("2023-08-09"), amount: 25487 },
      { date: new Date("2024-01-05"), amount: 32587 },
      { date: new Date(), amount: 747487 },
    ],
    isAvailable: false,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: false,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: false,
    isSelected: false,
  },
  {
    id: "vln04",
    firstName: "Ruth",
    secondName: "Great",
    avatar: "https://www.flaticon.com/free-icon/doctor_14244662",
    age: 12,
    address: "Street, Town",
    country: "England",
    sex: "female",
    phone: "+3803581454",
    donation: [{ date: new Date(), amount: 950000 }],
    isAvailable: true,
    isHasAnimalRescueExperience: false,
    isHasDriverLicence: false,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: false,
    isSelected: false,
  },
  {
    id: "vln05",
    firstName: "May",
    secondName: "Lee",
    avatar: "https://www.flaticon.com/free-icon/teacher_12404120",
    age: 39,
    address: "Street, Town",
    country: "Sweden",
    sex: "female",
    phone: "+38035468854",
    donation: [
      { date: new Date("2022-06-11"), amount: 7487 },
      { date: new Date("2022-03-02"), amount: 10000 },
      { date: new Date("2023-07-25"), amount: 250000 },
      { date: new Date(), amount: 375000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: false,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: false,
    isSelected: false,
  },
  {
    id: "vln06",
    firstName: "Gareth",
    secondName: "White",
    avatar: "https://www.flaticon.com/free-icon/teacher_12404093",
    age: 68,
    address: "Street, Town",
    country: "England",
    sex: "male",
    phone: "+380222468854",
    donation: [],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln07",
    firstName: "Katara",
    secondName: "Rose",
    avatar: "https://www.flaticon.com/free-icon/customer-service_12456948",
    age: 44,
    address: "Street, Town",
    country: "Poland",
    sex: "female",
    phone: "+385654558887",
    donation: [{ date: new Date(), amount: 3267 }],
    isAvailable: false,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: false,
    isHasPsychologicalExperience: false,
    isHasVetExperience: false,
    isSelected: false,
  },
  {
    id: "vln08",
    firstName: "Arthur",
    secondName: "Madison",
    avatar: "https://www.flaticon.com/free-icon/caregiver_12631745",
    age: 41,
    address: "Street, Town",
    country: "Ukraine",
    sex: "male",
    phone: "+3807812350",
    donation: [
      { date: new Date("2023-11-01"), amount: 500 },
      { date: new Date(), amount: 8920 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: false,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: false,
    isSelected: false,
  },
  {
    id: "vln09",
    firstName: "Dori",
    secondName: "Aang",
    avatar: "https:https://www.flaticon.com/free-icon/teacher_12404113",
    age: 40,
    address: "Street, Town",
    country: "Ukraine",
    sex: "female",
    phone: "+380045748887",
    donation: [
      { date: new Date("2022-02-22"), amount: 10000 },
      { date: new Date("2023-06-08"), amount: 20000 },
      { date: new Date(), amount: 45000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: false,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: false,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln10",
    firstName: "Robert",
    secondName: "Kovalsky",
    avatar: "https://www.flaticon.com/free-icon/deceased_12402138",
    age: 47,
    address: "Street, Town",
    country: "Poland",
    sex: "male",
    phone: "+38099887",
    donation: [{ date: new Date(), amount: 3267 }],
    isAvailable: true,
    isHasAnimalRescueExperience: false,
    isHasDriverLicence: false,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: false,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln11",
    firstName: "Max",
    secondName: "Gordeev",
    avatar: "https://www.flaticon.com/free-icon/man_2202112",
    age: 28,
    address: "Street, Town",
    country: "Ukraine",
    sex: "male",
    phone: "+38004500887",
    donation: [
      { date: new Date("2022-03-01"), amount: 55000 },
      { date: new Date("2022-11-01"), amount: 23000 },
      { date: new Date("2023-12-01"), amount: 250000 },
      { date: new Date(), amount: 400000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: false,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: false,
    isSelected: false,
  },
  {
    id: "vln12",
    firstName: "Roger",
    secondName: "Smilton",
    avatar: "https://www.flaticon.com/free-icon/gamer_4333609",
    age: 29,
    address: "Street, Town",
    country: "Poland",
    sex: "male",
    phone: "+380124558887",
    donation: [
      { date: new Date("2023-03-01"), amount: 20000 },
      { date: new Date(), amount: 35000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: false,
    isHasMedicalExperience: false,
    isHasPsychologicalExperience: false,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln13",
    firstName: "Angy",
    secondName: "Sokolova",
    avatar: "https://www.flaticon.com/free-icon/woman_4140047",
    age: 37,
    address: "Street, Town",
    country: "Ukraine",
    sex: "female",
    phone: "+38004558222",
    donation: [
      { date: new Date("2023-08-01"), amount: 200 },
      { date: new Date("2023-11-01"), amount: 9000 },
      { date: new Date(), amount: 25000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln14",
    firstName: "Tony",
    secondName: "Ratt",
    avatar: "https://www.flaticon.com/free-icon/man_4140048",
    age: 43,
    address: "Street, Town",
    country: "UK",
    sex: "male",
    phone: "+3800687152",
    donation: [{ date: new Date("2023-11-01"), amount: 6000 }],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: false,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln15",
    firstName: "Cody",
    secondName: "Royal",
    avatar: "https://www.flaticon.com/free-icon/boy_1999625",
    age: 32,
    address: "Street, Town",
    country: "Sweden",
    sex: "male",
    phone: "+38004567487",
    donation: [
      { date: new Date("2022-03-01"), amount: 1000000 },
      { date: new Date("2022-06-01"), amount: 950000 },
      { date: new Date("2022-11-01"), amount: 1500000 },
      { date: new Date("2023-01-01"), amount: 750000 },
      { date: new Date("2023-07-01"), amount: 250500 },
      { date: new Date("2023-11-01"), amount: 2500000 },
      { date: new Date(), amount: 3500500 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: false,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln16",
    firstName: "Sally",
    secondName: "Moon",
    avatar: "https://www.flaticon.com/free-icon/human_11498793",
    age: 23,
    address: "Street, Town",
    country: "UK",
    sex: "female",
    phone: "+380244558887",
    donation: [
      { date: new Date("2023-11-26"), amount: 56934 },
      { date: new Date(), amount: 9125 },
    ],
    isAvailable: false,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln17",
    firstName: "Leile",
    secondName: "Sonta",
    avatar: "https://www.flaticon.com/free-icon/woman_4140051",
    age: 36,
    address: "Street, Town",
    country: "Ukraine",
    sex: "female",
    phone: "+38004554448",
    donation: [
      { date: new Date("2022-10-24"), amount: 10000 },
      { date: new Date(), amount: 5000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: false,
    isHasPsychologicalExperience: true,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln18",
    firstName: "Onya",
    secondName: "Phillips",
    avatar: "https://www.flaticon.com/free-icon/woman_706831",
    age: 18,
    address: "Street, Town",
    country: "England",
    sex: "female",
    phone: "+38872558887",
    donation: [
      { date: new Date("2022-02-22"), amount: 2000 },
      { date: new Date("2022-03-18"), amount: 500 },
      { date: new Date("2023-07-12"), amount: 820 },
      { date: new Date("2023-10-14"), amount: 2500 },
      { date: new Date("2023-02-03"), amount: 360 },
      { date: new Date("2023-11-01"), amount: 467 },
      { date: new Date(), amount: 3950 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: false,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln19",
    firstName: "Toph",
    secondName: "Orlova",
    avatar: "https://www.flaticon.com/free-icon/woman_4140040",
    age: 28,
    address: "Street, Town",
    country: "Ukraine",
    sex: "female",
    phone: "+38003574",
    donation: [
      { date: new Date("2023-12-01"), amount: 8750 },
      { date: new Date(), amount: 10000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: false,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: true,
    isSelected: false,
  },
  {
    id: "vln20",
    firstName: "Chris",
    secondName: "Ankrovski",
    avatar: "https://www.flaticon.com/free-icon/man_4140061",
    age: 31,
    address: "Street, Town",
    country: "Poland",
    sex: "male",
    phone: "+38004500887",
    donation: [{ date: new Date(), amount: 250000 }],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: true,
    isHasVetExperience: false,
    isSelected: false,
  },
  {
    id: "vln21",
    firstName: "William",
    secondName: "Todd",
    avatar: "https://www.flaticon.com/free-icon/man_4140048",
    age: 24,
    address: "Street, Town",
    country: "England",
    sex: "male",
    phone: "+3800428887",
    donation: [
      { date: new Date("2022-11-04"), amount: 820000 },
      { date: new Date(), amount: 940000 },
    ],
    isAvailable: true,
    isHasAnimalRescueExperience: true,
    isHasDriverLicence: true,
    isHasMedicalExperience: true,
    isHasPsychologicalExperience: false,
    isHasVetExperience: true,
    isSelected: false,
  },
];
